version: '3'
services:
  build:
    image: circleci/golang:1.17.5
    entrypoint: /bin/sh
    command:
      - -c
      - |
        go mod download && \
        mkdir /tmp/artifacts && \
        CGO_ENABLED=0 go build -o /tmp/artifacts/archive_overlay -a -ldflags '-extldflags "-static"' . && \
        mkdir -p ./artifacts && \
        mv /tmp/artifacts/archive_overlay* ./artifacts/
    user: root
    working_dir: /project/
    volumes:
      - .:/project/
  test-fuse-mount:
    build: .
    command:
    - /bin/sh
    - "-c"
    - |
      python -m pytest -svvv ./tests || cat /var/log/syslogd/everything/current
    working_dir: /project
    privileged: true
    volumes:
    - .:/project
    - ./artifacts/archive_overlay:/usr/bin/archive_overlay:ro
    - ./configs/archive-overlay-debug.json:/usr/share/containers/oci/hooks.d/archive-overlay.json:ro
    - ./tests/data/fuse-storage.conf:/etc/containers/storage.conf
    depends_on:
      - build
  test-native-mount:
    build: .
    command:
    - /bin/sh
    - "-c"
    - |
      python -m pytest -svvv ./tests || cat /var/log/syslogd/everything/current
    working_dir: /project
    privileged: true
    volumes:
    - .:/project
    - ./artifacts/archive_overlay:/usr/bin/archive_overlay:ro
    - ./configs/archive-overlay-debug.json:/usr/share/containers/oci/hooks.d/archive-overlay.json:ro
    - ./tests/data/mount-storage.conf:/etc/containers/storage.conf
    depends_on:
      - build
